/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const UsersNewLazyImport = createFileRoute('/users/new')()
const UsersUserIdUpdateLazyImport = createFileRoute('/users/$userId/update')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const UsersNewLazyRoute = UsersNewLazyImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/users/new.lazy').then((d) => d.Route))

const UsersUserIdUpdateLazyRoute = UsersUserIdUpdateLazyImport.update({
  id: '/users/$userId/update',
  path: '/users/$userId/update',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/users/$userId/update.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/users/new': {
      id: '/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/users/$userId/update': {
      id: '/users/$userId/update'
      path: '/users/$userId/update'
      fullPath: '/users/$userId/update'
      preLoaderRoute: typeof UsersUserIdUpdateLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/users/new': typeof UsersNewLazyRoute
  '/users/$userId/update': typeof UsersUserIdUpdateLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/users/new': typeof UsersNewLazyRoute
  '/users/$userId/update': typeof UsersUserIdUpdateLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/users/new': typeof UsersNewLazyRoute
  '/users/$userId/update': typeof UsersUserIdUpdateLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/users/new' | '/users/$userId/update'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/users/new' | '/users/$userId/update'
  id: '__root__' | '/' | '/users/new' | '/users/$userId/update'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  UsersNewLazyRoute: typeof UsersNewLazyRoute
  UsersUserIdUpdateLazyRoute: typeof UsersUserIdUpdateLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  UsersNewLazyRoute: UsersNewLazyRoute,
  UsersUserIdUpdateLazyRoute: UsersUserIdUpdateLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/users/new",
        "/users/$userId/update"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/users/new": {
      "filePath": "users/new.lazy.tsx"
    },
    "/users/$userId/update": {
      "filePath": "users/$userId/update.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
